#!/bin/bash

cmd=$1
commit=$(git rev-parse --short HEAD)

if [[ $cmd == "build" ]]; then
  echo "building simple-news:$commit"
  docker build . -t simple-news:$commit
elif [[ $cmd == "run" ]]; then
  echo "running simple-news:$commit"
  docker run \
    --rm \
    --init \
    --volume "./server:/data" \
    --env "DATABASE_URL=sqlite:///data/database.db" \
    --env "RUST_LOG=simple_news=debug,tower_http=debug,info" \
    -p 3333:3333 \
    simple-news:$commit
elif [[ $cmd == "publish" ]]; then
  echo "publishing simple-news:$commit"
  docker tag simple-news:$commit ghcr.io/jason0x43/simple-news:$commit
  echo "tagged simple-news:$commit as ghcr.io/jason0x43/simple-news:$commit"
  docker push ghcr.io/jason0x43/simple-news:$commit
else
  echo "unknown command '$cmd'"
  echo "usage: $0 <build|run>"
  exit 1
fi
