#!/bin/sh

args=""
mode=prod
serve=0

if [ "$1" = "serve" ]; then
	serve=1
fi

for arg in $@; do
	if [ "$arg" = "-d" ] || [ "$arg" = "--dev" ]; then
		mode=dev
	fi

	if [ "$args" = "" ]; then
		args=$arg
	else
		args="$args $arg"
	fi
done

cmd="deno run"
cmd="$cmd --allow-net"
cmd="$cmd --allow-env"
cmd="$cmd --allow-read"
cmd="$cmd --allow-write=data.db,data.db-journal"
cmd="$cmd --unstable"

if [ "$mode" = "dev" ]; then
	if [ "$serve" ]; then
		cmd="$cmd --watch --no-clear-screen --allow-run=touch"
	fi
	cmd="$cmd --no-check=remote --import-map=import_map_dev.json"
else
	cmd="$cmd --no-check --lock=lock.json"
	export SN_IMPORT_MAP="import_map.json"
fi

eval $cmd mod.ts $args
