#!/bin/sh

args=""
mode=prod
serve=0

if [ "$1" = "serve" ]; then
	serve=1
fi

for arg in $@; do
	if [ "$arg" = "-d" ] || [ "$arg" = "--dev" ]; then
		mode=dev
	elif [ "$args" = "" ]; then
		args=$arg
	else
		args="$args $arg"
	fi
done

cmd="deno run"
cmd="$cmd --allow-net"
cmd="$cmd --allow-env"
cmd="$cmd --allow-read"
cmd="$cmd --allow-write=data.db,data.db-journal"
cmd="$cmd --unstable"

if [ "$mode" = "dev" ]; then
	if [ "$serve" ]; then
		echo "Enabling watch mode"
		cmd="$cmd --watch --no-clear-screen --allow-run=touch"
	fi
	cmd="$cmd --no-check"
	echo "Using dev import map"
	export SN_IMPORT_MAP="import_map_dev.json"
	export SN_MODE="dev"
else
	cmd="$cmd --no-check"
	echo "Using prod import map"
	export SN_IMPORT_MAP="import_map.json"
fi

eval $cmd --import-map ./$SN_IMPORT_MAP mod.ts $args
