// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.account */
export type AccountId = string & { __brand: 'AccountId' };

/** Represents the table public.account */
export default interface AccountTable {
  id: ColumnType<AccountId, AccountId, AccountId>;

  email: ColumnType<string, string, string>;

  username: ColumnType<string, string, string>;

  config: ColumnType<unknown | null, unknown | null, unknown | null>;
}

export type Account = Selectable<AccountTable>;

export type NewAccount = Insertable<AccountTable>;

export type AccountUpdate = Updateable<AccountTable>;
