// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountId } from "./Account.js";
import type { ArticleId } from "./Article.js";
import type { ColumnType, Selectable, Insertable, Updateable } from "kysely";

/** Represents the table public.account_article */
export default interface AccountArticleTable {
	account_id: ColumnType<AccountId, AccountId, AccountId>;

	article_id: ColumnType<ArticleId, ArticleId, ArticleId>;

	_id: ColumnType<string | null, string | null, string | null>;

	read: ColumnType<boolean, boolean | undefined, boolean>;

	saved: ColumnType<boolean, boolean | undefined, boolean>;
}

export type AccountArticle = Selectable<AccountArticleTable>;

export type NewAccountArticle = Insertable<AccountArticleTable>;

export type AccountArticleUpdate = Updateable<AccountArticleTable>;
