// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountId } from './Account';
import type { ArticleId } from './Article';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.account_article */
export type AccountArticleId = string & { __brand: 'AccountArticleId' };

/** Represents the table public.account_article */
export default interface AccountArticleTable {
  id: ColumnType<AccountArticleId, AccountArticleId, AccountArticleId>;

  account_id: ColumnType<AccountId, AccountId, AccountId>;

  article_id: ColumnType<ArticleId, ArticleId, ArticleId>;

  read: ColumnType<boolean, boolean | undefined, boolean>;

  saved: ColumnType<boolean, boolean | undefined, boolean>;
}

export type AccountArticle = Selectable<AccountArticleTable>;

export type NewAccountArticle = Insertable<AccountArticleTable>;

export type AccountArticleUpdate = Updateable<AccountArticleTable>;
