// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FeedId } from './Feed.js';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.article */
export type ArticleId = string & { __brand: 'ArticleId' };

/** Represents the table public.article */
export default interface ArticleTable {
  id: ColumnType<ArticleId, ArticleId, ArticleId>;

  article_id: ColumnType<string, string, string>;

  feed_id: ColumnType<FeedId, FeedId, FeedId>;

  title: ColumnType<string, string, string>;

  content: ColumnType<string, string, string>;

  published: ColumnType<Date, Date | string, Date | string>;

  link: ColumnType<string | null, string | null, string | null>;
}

export type Article = Selectable<ArticleTable>;

export type NewArticle = Insertable<ArticleTable>;

export type ArticleUpdate = Updateable<ArticleTable>;
