// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FeedGroupId } from "./FeedGroup.js";
import type { FeedId } from "./Feed.js";
import type { ColumnType, Selectable, Insertable, Updateable } from "kysely";

/** Represents the table public.feed_group_feed */
export default interface FeedGroupFeedTable {
	feed_group_id: ColumnType<FeedGroupId, FeedGroupId, FeedGroupId>;

	feed_id: ColumnType<FeedId, FeedId, FeedId>;
}

export type FeedGroupFeed = Selectable<FeedGroupFeedTable>;

export type NewFeedGroupFeed = Insertable<FeedGroupFeedTable>;

export type FeedGroupFeedUpdate = Updateable<FeedGroupFeedTable>;
