// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountId } from './Account.js';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.feed_group */
export type FeedGroupId = string & { __brand: 'FeedGroupId' };

/** Represents the table public.feed_group */
export default interface FeedGroupTable {
  id: ColumnType<FeedGroupId, FeedGroupId, FeedGroupId>;

  account_id: ColumnType<AccountId, AccountId, AccountId>;

  name: ColumnType<string, string, string>;
}

export type FeedGroup = Selectable<FeedGroupTable>;

export type NewFeedGroup = Insertable<FeedGroupTable>;

export type FeedGroupUpdate = Updateable<FeedGroupTable>;
