// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FeedId } from "./Feed.js";
import type { ColumnType, Selectable, Insertable, Updateable } from "kysely";

/** Identifier type for public.feed_log */
export type FeedLogId = string & { __brand: "FeedLogId" };

/** Represents the table public.feed_log */
export default interface FeedLogTable {
	id: ColumnType<FeedLogId, FeedLogId, FeedLogId>;

	feed_id: ColumnType<FeedId, FeedId, FeedId>;

	time: ColumnType<Date, Date | string, Date | string>;

	success: ColumnType<boolean, boolean, boolean>;

	message: ColumnType<string | null, string | null, string | null>;
}

export type FeedLog = Selectable<FeedLogTable>;

export type NewFeedLog = Insertable<FeedLogTable>;

export type FeedLogUpdate = Updateable<FeedLogTable>;
