// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountId } from './Account.js';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.password */
export type PasswordId = string & { __brand: 'PasswordId' };

/** Represents the table public.password */
export default interface PasswordTable {
  id: ColumnType<PasswordId, PasswordId, PasswordId>;

  account_id: ColumnType<AccountId, AccountId, AccountId>;

  hash: ColumnType<string, string, string>;

  salt: ColumnType<string, string, string>;
}

export type Password = Selectable<PasswordTable>;

export type NewPassword = Insertable<PasswordTable>;

export type PasswordUpdate = Updateable<PasswordTable>;
