// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as SqlxMigrationsTable } from "./SqlxMigrations";
import type { default as AccountTable } from "./Account";
import type { default as SessionTable } from "./Session";
import type { default as PasswordTable } from "./Password";
import type { default as FeedTable } from "./Feed";
import type { default as AccountArticleTable } from "./AccountArticle";
import type { default as FeedLogTable } from "./FeedLog";
import type { default as FeedGroupTable } from "./FeedGroup";
import type { default as FeedGroupFeedTable } from "./FeedGroupFeed";
import type { default as ArticleTable } from "./Article";

export default interface PublicSchema {
	_sqlx_migrations: SqlxMigrationsTable;

	account: AccountTable;

	session: SessionTable;

	password: PasswordTable;

	feed: FeedTable;

	account_article: AccountArticleTable;

	feed_log: FeedLogTable;

	feed_group: FeedGroupTable;

	feed_group_feed: FeedGroupFeedTable;

	article: ArticleTable;
}
