// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountId } from './Account.js';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.session */
export type SessionId = string & { __brand: 'SessionId' };

/** Represents the table public.session */
export default interface SessionTable {
  id: ColumnType<SessionId, SessionId, SessionId>;

  account_id: ColumnType<AccountId, AccountId, AccountId>;

  data: ColumnType<unknown | null, unknown | null, unknown | null>;

  expires: ColumnType<Date, Date | string, Date | string>;
}

export type Session = Selectable<SessionTable>;

export type NewSession = Insertable<SessionTable>;

export type SessionUpdate = Updateable<SessionTable>;
