// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public._sqlx_migrations */
export type SqlxMigrationsVersion = string & { __brand: 'SqlxMigrationsVersion' };

/** Represents the table public._sqlx_migrations */
export default interface SqlxMigrationsTable {
  version: ColumnType<SqlxMigrationsVersion, SqlxMigrationsVersion, SqlxMigrationsVersion>;

  description: ColumnType<string, string, string>;

  installed_on: ColumnType<Date, Date | string | undefined, Date | string>;

  success: ColumnType<boolean, boolean, boolean>;

  checksum: ColumnType<Uint8Array, Uint8Array, Uint8Array>;

  execution_time: ColumnType<string, string, string>;
}

export type SqlxMigrations = Selectable<SqlxMigrationsTable>;

export type NewSqlxMigrations = Insertable<SqlxMigrationsTable>;

export type SqlxMigrationsUpdate = Updateable<SqlxMigrationsTable>;
